/**
 * Drifting cumulus sprites (textures generated by tools/gen_textures.py). They sit in depth
 * layers behind the object, drift slowly, parallax with scroll and pointer, and take their
 * colour from the sky: white at noon, apricot at golden hour, violet-grey at dusk.
 */
import { Color, Group, SRGBColorSpace, Sprite, SpriteMaterial, TextureLoader, Vector3, type Texture } from 'three';
import type { SkyBlend } from './sky';

interface Cloud {
  sprite: Sprite;
  base: Vector3;
  speed: number;
  depth: number;
}

function seeded(seed: number) {
  let s = seed;
  return () => ((s = (s * 16807) % 2147483647) / 2147483647);
}

export class CloudField {
  readonly group = new Group();
  private clouds: Cloud[] = [];
  private tint = new Color();
  private white = new Color(1, 1, 1);

  constructor(textureBase: string, count = 11) {
    const loader = new TextureLoader();
    const textures: Texture[] = Array.from({ length: 6 }, (_, i) => {
      const t = loader.load(`${textureBase}cloud-${i}.webp`);
      t.colorSpace = SRGBColorSpace;
      return t;
    });
    const rnd = seeded(42);
    for (let i = 0; i < count; i++) {
      const depth = 0.25 + rnd() * 0.75; // 0 near … 1 far
      const mat = new SpriteMaterial({
        map: textures[i % textures.length]!,
        transparent: true,
        depthWrite: false,
        fog: false,
        toneMapped: false,
        opacity: 0,
      });
      const sprite = new Sprite(mat);
      const w = 5 + rnd() * 5 + (1 - depth) * 3;
      sprite.scale.set(w, w / 2, 1);
      const base = new Vector3((rnd() - 0.5) * 22, (rnd() - 0.35) * 10, -4 - depth * 16);
      sprite.position.copy(base);
      sprite.renderOrder = -10;
      this.group.add(sprite);
      this.clouds.push({ sprite, base, speed: 0.05 + rnd() * 0.12, depth });
    }
  }

  update(time: number, scroll: number, pointer: { x: number; y: number }, sky: SkyBlend) {
    // Tint: sunlit side of the palette blended with the sky's own middle colour.
    this.tint.setRGB(sky.sun.x, sky.sun.y, sky.sun.z, 'srgb-linear').lerp(this.white, 0.55);
    const ambient = new Color().setRGB(sky.mid.x, sky.mid.y, sky.mid.z, 'srgb-linear');
    this.tint.lerp(ambient, 0.25 + sky.dark * 0.45);
    this.tint.multiplyScalar(1.3 - sky.dark * 0.8);

    for (const c of this.clouds) {
      const parallax = 1.4 - c.depth;
      const span = 26;
      let x = c.base.x + time * c.speed + pointer.x * parallax * 0.6;
      x = ((x + span / 2) % span + span) % span - span / 2;
      // Scrolling the page flies the camera up through the day: near clouds move faster.
      const y = c.base.y + scroll * (5 + parallax * 9) + pointer.y * parallax * 0.3;
      const wrapped = ((y + 12) % 26 + 26) % 26 - 12;
      c.sprite.position.set(x, wrapped, c.base.z);
      const mat = c.sprite.material;
      mat.color.copy(this.tint);
      mat.opacity = sky.clouds * (0.55 + (1 - c.depth) * 0.45);
    }
  }
}
